stages:
  - build
  - test
  - checkstyle
  - deploy

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - mvn clean package

checkstyle:
    stage: checkstyle
    image: maven:3.3.9-jdk-8
    script:
    - echo "Checkstyle DEMO app"
    - mvn checkstyle:check

variables:
    DB_IP: ec2-54-228-99-58.eu-west-1.compute.amazonaws.com
    DB_PORT: 5432
    DB_USER: rgivldouljbfhc
    DB_PASSWORD: c78da37a39ed7655d361cfb42273a7d27c28d062992ed28ba2b5739d66c656f8
    DB_DBNAME: d5ftiu17o66bjo
    
deploy:
  stage: deploy
  image: ruby:2.4
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=ds2021-app-vamvu-denisa --api-key=$HEROKU_API_KEY
  only:
    - production
